---
- name: playbook ejemplo
  hosts: all

  tasks:
  - name: revisar usuarios
    command: cat /etc/passwd | cut -d: -f1 | tr "," "\n"
    register: lista_users

  - name: imprimir lista usuarios
    debug: 
      var: lista_users.stdout 


